# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#    object_normalizer:
#            class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
#            tags:
#            # помечаем к чему относится этот сервис, это оч. важно, т.к. иначе работать не будет
#              - { name: serializer.normalizer }
    acme.encoder.json:
            class: Symfony\Component\Serializer\Encoder\JsonEncoder
    # Bookmark Normalizer
    acme.normalizer.bookmark:
            class: BookmarksBundle\Serializer\Normalizer\Bookmark
    # Serializer
    acme.serializer.default:
            class: Symfony\Component\Serializer\Serializer
            arguments:
                0:
                    - '@acme.normalizer.bookmark'
                    - '@serializer.normalizer.object'
                1:
                    - '@acme.encoder.json'
